[Icon Theme]
Name=Zafiro-icons-Light
Comment=icon theme flat for gnome,xfce and lxde
Comment[es]=tema de iconos planos y sobrios.
Comment[zh_TW]=清醒和平面图标的主题
Inherits=Surfn,Adwaita,Numix,Numix-Circle-Light,Numix-Circle,breeze,gnome,hicolor

PanelDefault=22
PanelSizes=22

# Directory list
Directories=panel/16,actions/16,

[panel/16]
Size=16
Context=Status
MinSize=8
MaxSize=21
Type=Scalable

[actions/16]
Size=16
Context=Actions
Type=Fixed